---
# default variables for peyotl tasks and template file

# task vars
#install_dir: /opt/otindex
peyotl_config_location: "/home/opentree/.peyotl"
#peyotl_branch: modern-taxalotl
# results in TypeError: 'dict_values' object does not support indexing
peyotl_branch: pyramid-adjacent-changes

# template vars
phylesystem_parent: "{{ install_dir }}/phylesystem-1_par"
phylesystem_location: "{{ phylesystem_parent }}/phylesystem-1"

repo_nexml2json: 1.2.1
ott_dir: "{{ install_dir }}/ott"
logging_level: debug
peyotl_logging_filepath: "{{ otindex_logfile_dir }}/peyotl.log"
logging_formatter: rich
